#version: "3"
#
services:
  iari:
    build: .
    image: iari
    ports:
      - "${PORT}:5000"
    volumes:
      - ./:/app  # maps local working directory to ./app
    env_file: .env
    command: poetry run gunicorn -w 9 --bind :5000 wsgi:app --timeout 1500
