import json
import logging
from unittest import TestCase

from flask import Flask
from flask_restful import Api  # type: ignore

from src.models.api.article_statistics import ArticleStatistics
from src.models.api.get_article_statistics import GetArticleStatistics

logger = logging.getLogger(__name__)

# This is needed to get the full diff when tests fail
# https://stackoverflow.com/questions/14493670/how-to-set-self-maxdiff-in-nose-to-get-full-diff-output
TestCase.maxDiff = None


class TestGetArticleStatistics(TestCase):
    """Generated by ChatGPT using this prompt:
        Create a test for this flask api endpoint
    import logging
    from typing import Optional

    from flask import request
    from flask_restful import Resource, abort  # type: ignore

    from src.helpers.console import console
    from src.models.api.get_statistics_schema import GetStatisticsSchema
    from src.models.api.job import Job
    from src.models.wikimedia.enums import AnalyzerReturn
    from src.models.wikimedia.wikipedia.analyzer import WikipediaAnalyzer

    logger = logging.getLogger(__name__)


    class GetArticleStatistics(Resource):
        schema = GetStatisticsSchema()
        job: Optional[Job]

        def get(self):
            self.__validate_and_get_job__()
            if self.job.lang.lower() == "en" and self.job.title and self.job.site.lower() == "wikipedia":
                logger.info(f"Analyzing {self.job.title}...")
                # TODO use a work queue here like ReFill so
                #  we can easily scale the workload from thousands of users
                wikipedia_analyzer = WikipediaAnalyzer(title=self.job.title,
                                                       lang=self.job.lang,
                                                       wikimedia_site=self.job.site,
                                                       testing=self.job.testing)
                statistics = wikipedia_analyzer.get_statistics()
                if self.job.testing:
                    # what is the purpose of this?
                    return "ok", 200
                else:
                    if isinstance(statistics, dict):
                        # we got a json response
                        # according to https://stackoverflow.com/questions/13081532/return-json-response-from-flask-view
                        # flask calls jsonify automatically
                        return statistics, 200
                    elif statistics == AnalyzerReturn.NOT_FOUND:
                        return statistics.value, 404
                    elif statistics == AnalyzerReturn.IS_REDIRECT:
                        return statistics.value, 400
                    else:
                        raise Exception("this should never be reached.")

            else:
                # Something was not valid, return a meaningful error
                logger.error("did not get what we need")
                if self.job.lang != "en":
                    return "Only en language code is supported", 400
                if self.job.title == "":
                    return "Title was missing", 400
                if self.job.site != "wikipedia":
                    return "Only 'wikipedia' site is supported", 400

        def __validate_and_get_job__(self):
            self.__validate__()
            self.__parse_into_job__()

        def __validate__(self):
            print(request.args)
            errors = self.schema.validate(request.args)
            if errors:
                abort(400, error=str(errors))

        def __parse_into_job__(self):
            console.print(request.args)
            self.job = self.schema.load(request.args)
            console.print(self.job.dict())

    from marshmallow import Schema, fields, post_load

    from src.models.api.job import Job


    class GetStatisticsSchema(Schema):
        lang = fields.Str(required=True)
        site = fields.Str(required=True)
        testing = fields.Bool(required=False)
        title = fields.Str(required=True)

        # noinspection PyUnusedLocal
        @post_load
        # **kwargs is needed here despite what the validator claims
        def return_object(self, data, **kwargs):  # type: ignore
            return Job(**data)
    """

    def setUp(self):
        app = Flask(__name__)
        api = Api(app)

        api.add_resource(GetArticleStatistics, "/get-statistics")
        app.testing = True
        self.test_client = app.test_client()

    def test_valid_request_test(self):
        response = self.test_client.get(
            "/get-statistics?lang=en&site=wikipedia&title=Test&testing=True"
        )
        data = json.loads(response.data)
        print(response.data)
        self.assertEqual(200, response.status_code)
        self.assertEqual(ArticleStatistics().dict(), ArticleStatistics(**data).dict())

    def test_valid_request_gnu_linux_naming_controversy(self):
        response = self.test_client.get(
            "get-statistics?lang=en&site=wikipedia&title=GNU/Linux_naming_controversy"
        )
        logger.debug(response.data)
        # data = json.loads(response.data)
        self.assertEqual(200, response.status_code)

    def test_valid_request_easter_island(self):
        response = self.test_client.get(
            "/get-statistics?lang=en&site=wikipedia&title=Easter Island&testing=True"
        )
        data = json.loads(response.data)
        self.assertEqual(200, response.status_code)
        self.assertEqual(
            {
                "first_level_domain_counts": {
                    "archive.org": 2,
                    "auckland.ac.nz": 1,
                    "censo2017.cl": 1,
                    "ine.cl": 1,
                },
                "number_of_bare_url_references": 0,
                "number_of_citation_references": 2,
                "number_of_citation_template_references": 0,
                "number_of_citeq_references": 0,
                "number_of_content_reference_with_at_least_one_template": 4,
                "number_of_content_reference_without_a_template": 0,
                "number_of_content_references": 4,
                "number_of_content_references_with_a_supported_template_we_prefer": 4,
                "number_of_content_references_with_any_supported_template": 4,
                "number_of_cs1_references": 4,
                "number_of_general_references": 2,
                "number_of_hashed_content_references": 4,
                "number_of_isbn_template_references": 0,
                "number_of_multiple_template_references": 0,
                "number_of_empty_named_references": 1,
                "number_of_url_template_references": 0,
                "percent_of_content_references_with_a_hash": 100,
                "percent_of_content_references_without_a_template": 0,
                "references": [
                    {
                        "bare_url_template_found": False,
                        "citation_template_found": False,
                        "citeq_template_found": False,
                        "cs1_template_found": True,
                        "is_citation_reference": True,
                        "is_general_reference": False,
                        "is_named_reference": False,
                        "isbn_template_found": False,
                        "multiple_templates_found": False,
                        "plain_text_in_reference": False,
                        "url_template_found": False,
                        "wikitext": '<ref name="INE">{{cite web | url= '
                        "http://www.ine.cl/canales/chile_estadistico/censos_"
                        "poblacion_vivienda/censo_pobl_vivi.php "
                        "| title= Censo de Población y Vivienda 2002 | "
                        "work= [[National Statistics Institute "
                        "(Chile)|National Statistics Institute]] | "
                        "access-date= 1 May 2010 | url-status=live | "
                        "archive-url= "
                        "https://web.archive.org/web/20100715195638/http://www.ine.cl/"
                        "canales/chile_estadistico/censos_poblacion_vivienda/censo_pobl_vivi.php "
                        "| archive-date= 15 July 2010}}</ref>",
                    },
                    {
                        "bare_url_template_found": False,
                        "citation_template_found": False,
                        "citeq_template_found": False,
                        "cs1_template_found": True,
                        "is_citation_reference": True,
                        "is_general_reference": False,
                        "is_named_reference": False,
                        "isbn_template_found": False,
                        "multiple_templates_found": False,
                        "plain_text_in_reference": False,
                        "url_template_found": False,
                        "wikitext": "<ref>{{cite web |language= es |url= "
                        "https://resultados.censo2017.cl/Home/Download "
                        "|title= Censo 2017 |work= [[National Statistics "
                        "Institute (Chile)|National Statistics "
                        "Institute]] |access-date= 11 May 2018 "
                        "|archive-url= "
                        "https://web.archive.org/web/20180511145942/https://"
                        "resultados.censo2017.cl/Home/Download "
                        "|archive-date= 11 May 2018 |url-status=dead "
                        "}}</ref>",
                    },
                    {
                        "bare_url_template_found": False,
                        "citation_template_found": False,
                        "citeq_template_found": False,
                        "cs1_template_found": False,
                        "is_citation_reference": True,
                        "is_general_reference": False,
                        "is_named_reference": True,
                        "isbn_template_found": False,
                        "multiple_templates_found": False,
                        "plain_text_in_reference": False,
                        "url_template_found": False,
                        "wikitext": '<ref name="INE"/>',
                    },
                    {
                        "bare_url_template_found": False,
                        "citation_template_found": False,
                        "citeq_template_found": False,
                        "cs1_template_found": True,
                        "is_citation_reference": False,
                        "is_general_reference": True,
                        "is_named_reference": False,
                        "isbn_template_found": False,
                        "multiple_templates_found": False,
                        "plain_text_in_reference": False,
                        "url_template_found": False,
                        "wikitext": "* {{cite book|author-link=Jared "
                        "Diamond|last=Diamond|first= "
                        "Jared|year=2005|title=Collapse. How Societies "
                        "Choose to Fail or Succeed|location=New "
                        "York|publisher=Viking|isbn=978-0143036555 "
                        "|title-link=Collapse (book)}}",
                    },
                    {
                        "bare_url_template_found": False,
                        "citation_template_found": False,
                        "citeq_template_found": False,
                        "cs1_template_found": True,
                        "is_citation_reference": False,
                        "is_general_reference": True,
                        "is_named_reference": False,
                        "isbn_template_found": False,
                        "multiple_templates_found": False,
                        "plain_text_in_reference": False,
                        "url_template_found": False,
                        "wikitext": "* {{cite journal|last= Fischer|first= Steven "
                        "Roger|year= 1995|title= Preliminary Evidence for "
                        "Cosmogonic Texts in Rapanui's Rongorongo "
                        "Inscriptions|journal= Journal of the Polynesian "
                        "Society "
                        "|issue=104|pages=303–21|url=http://www.jps.auckland.ac.nz/document/"
                        "Volume_104_1995/Volume_104%2C_No._3/Preliminary_evidence_for_cosmogonic_"
                        "texts_in_Rapanui%26apos%3Bs_Rongorongo_inscriptions%2C_by_"
                        "Steven_Roger_Fischer%2C_p_303-322/p1}}",
                    },
                ],
            },
            ArticleStatistics(**data).dict(),
        )

    def test_invalid_language(self):
        response = self.test_client.get(
            "/get-statistics?lang=fr&site=wikipedia&title=Test"
        )
        self.assertEqual(response.status_code, 400)
        self.assertEqual(
            response.data, b'"Only en language code is supported"\n'
        )  # expected output

    def test_missing_title(self):
        response = self.test_client.get("/get-statistics?lang=en&site=wikipedia")
        self.assertEqual(response.status_code, 400)
        self.assertEqual(
            response.data,
            b"{\"error\": \"{'title': ['Missing data for required field.']}\"}\n",
        )

    def test_invalid_site(self):
        response = self.test_client.get(
            "/get-statistics?lang=en&site=example.com&title=Test"
        )
        print(response.data)
        self.assertEqual(400, response.status_code)
        self.assertEqual(
            b"{\"error\": \"{'site': ['Must be one of: wikipedia.']}\"}\n",
            response.data,
        )

    def test_site_capitalized(self):
        response = self.test_client.get(
            "/get-statistics?lang=en&site=WIKIPEDIA&title=Test"
        )
        # print(response.data)
        self.assertEqual(400, response.status_code)

    def test_valid_site(self):
        response = self.test_client.get(
            "/get-statistics?lang=en&site=wikipedia&title=Test"
        )
        # print(response.data)
        self.assertEqual(200, response.status_code)
