@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor User as user
control wcdimportbot
database "Cache/SPARQL" as Cache
database WikiCitations
entity "Wikipedia API" as wikipediaapi
user -> wcdimportbot: Run the bot using --range
wcdimportbot -> wikipediaapi: Get range of pages
loop for each page
    wcdimportbot -> Cache: Lookup page hash and WCDQID
    alt "page hash not found"
        wcdimportbot -> wcdimportbot: Parse templates into objects
        loop for each reference
            wcdimportbot -> wcdimportbot: tokenize/hash the reference
            wcdimportbot -> Cache: Lookup reference hash
            Cache -> wcdimportbot: Response
            alt reference hash found
                wcdimportbot -> wcdimportbot: Link to existing reference
            end
            alt reference hash not found
                alt URL found
                    wcdimportbot -> wcdimportbot: Generate website item
                    wcdimportbot -> Cache: Insert website item hash and WCDQID
                    wcdimportbot -> WikiCitations: Create new website item
                end
                wcdimportbot -> wcdimportbot: Generate the statements
                wcdimportbot -> Cache: Insert reference hash and WCDQID
                wcdimportbot -> WikiCitations: Create new item for the reference
                WikiCitations -> wcdimportbot: Response with WCDQID
            end
        end
        wcdimportbot -> Cache: Insert page hash and WCDQID
        wcdimportbot -> wcdimportbot: Generate the statements
        wcdimportbot -> WikiCitations: Create new item for the page with links to all references
    end
end
@enduml