@startuml
'https://plantuml.com/class-diagram

class parameters{
## all ~100 parameters in CS1 templates
## (all hyphens are converted to underscores)
doi: str
isbn: str
hdl: str
title: str
...
}
class wikidata_details{
fulltext_url: str
publisher: wdqid
journal: wdqid
authors: List[author1_qid, ...]
author_strings: int}
}
class article{
wari_id: str
reference_statistics: Dict[str, int]
references: List[dehydrated_reference]
title: str
page_id: int
urls: List[str]
dois: List[str]
fld_counts: Dict[str, int] # e.g. {archive.org: 2}
}
class references{
ids: List[str]
}
class reference{
templates: List[Template]
wikitext: str
}
class dehydrated_reference {
id: str
titles: List[str]
identifiers: Dict[str, List[str]]
urls: List[str]
}
dehydrated_reference <-- reference
class check-url{
"url": "",
"host": "",
"domain": "",
"suffix": "",
"tld": "", # top level domain
"status": "",
"checked": isodate
error: bool
fixed: str
}
class check-doi{
doi: str
retracted_in: Dict[str: bool] # e.g. {openalex: true, open-retractions: false}
wikidata_qid: str
wikidata_details: Dict[str, Any]
}
class template{
title: str
parameters: Dict[str, Any]
persons: List[Person]
}
class person{
role: Enum
orcid: str
# todo check these:
first_name: str
last_name: str
}
enum role{
author
translator
editor
no_role
}
@enduml