@startuml
'https://plantuml.com/component-diagram

[WARI] -- references
[WARI] -- "reference/id"
[WARI] -- "check-url"
"check-url" --> url : lookup
[WARI] -- "check-doi"
[WARI] -- "article"
"check-doi" --> OpenAlex : lookup
"check-doi" --> FatCat : lookup
"check-doi" --> Wikidata : lookup
[WARI] -- all
"reference/id" <-- all
"check-doi" <-- all
"check-url" <-- all
"article" <-- all

database "file system" {

  folder "references/" {
  }
  folder "articles/" {
  }
  folder "urls/" {
  }
  folder "dois/" {
  }

}
@enduml