@startuml
'https://plantuml.com/class-diagram

abstract class BaseModel

BaseModel <|-- Cache
BaseModel <|-- SsdbDatabase
BaseModel <|-- Person
BaseModel <|-- WikipediaPage
BaseModel <|-- WikipediaPageReference
BaseModel <|-- WikipediaPageReferenceSchema
WikipediaPageReferenceSchema <|-- EnglishWikipediaPageReferenceSchema
BaseException <|-- TimeParseException
BaseException <|-- MoreThanOneNumberError


class EnglishWikipediaPageReferenceSchema{
return_object()
}

class WikipediaPageReferenceSchema{
first_parameter
second_parameter
template_name
}

class WikipediaPageReference {
access_date
agency
archive_date
archive_format
archive_url
arxiv
asin
asin_tld
at
author
author1
author10
author1_first
author1_last
author1_link
author2
author2_first
author2_last
author2_link
author3
author3_first
author3_last
author3_link
author4
author4_first
author4_last
author4_link
author5
author5_first
author5_last
author5_link
author6
author7
author8
author9
author_first
author_first1
author_first2
author_first3
author_first4
author_first5
author_given
author_given1
author_given2
author_given3
author_given4
author_given5
author_last
author_last1
author_last2
author_last3
author_last4
author_last5
author_link
author_link1
author_link2
author_link3
author_link4
author_link5
author_mask
author_mask1
author_mask2
author_mask3
author_mask4
author_mask5
author_surname
author_surname1
author_surname2
author_surname3
author_surname4
author_surname5
authors
bibcode
bibcode_access
biorxiv
book_title
chapter
chapter_format
chapter_url
chapter_url_access
citeseerx
conference
conference_url
contribution
date
degree
department
df
display_authors
display_editors
display_subjects
display_translators
doi
doi_access
doi_broken_date
edition
editor
editor1
editor1_first
editor1_last
editor1_link
editor2
editor2_first
editor2_last
editor2_link
editor3
editor3_first
editor3_last
editor3_link
editor4
editor4_first
editor4_last
editor4_link
editor5
editor5_first
editor5_last
editor5_link
editor_first
editor_first1
editor_first2
editor_first3
editor_first4
editor_first5
editor_last
editor_last1
editor_last2
editor_last3
editor_last4
editor_last5
editor_link
editor_link1
editor_link2
editor_link3
editor_link4
editor_link5
editor_mask
editor_mask1
editor_mask2
editor_mask3
editor_mask4
editor_mask5
editors
eissn
encyclopedia
eprint
first
first1
first10
first2
first3
first4
first5
first6
first7
first8
first9
first_parameter
format
hdl
hdl_access
host
host1
host2
host3
host4
host5
hosts
id
interviewer
interviewer_first
interviewer_given
interviewer_last
interviewer_surname
interviewers
isbn
ismn
issn
issue
jfm
journal
jstor
jstor_access
language
last
last1
last10
last2
last3
last4
last5
last6
last7
last8
last9
lay_date
lay_format
lay_source
lay_url
lccn
location
magazine
medium
message_id
mode
mr
name_list_style
news_class
newsgroup
newspaper
no_pp
number
oclc
ol
ol_access
orig_date
orig_year
osti
osti_access
others
page
pages
persons_without_role
pmc
pmc_embargo_date
pmid
postscript
publication_date
publication_place
publisher
quote
quote_page
quote_pages
ref
registration
rfc
s2cid
s2cid_access
sbn
script_chapter
script_quote
script_title
second_parameter
series
ssrn
subject
subject_mask
subscription
template_name
time
title
title_link
trans_chapter
trans_quote
trans_title
transcripturl
translator_first
translator_first1
translator_first2
translator_first3
translator_first4
translator_first5
translator_last
translator_last1
translator_last2
translator_last3
translator_last4
translator_last5
translator_link
translator_link1
translator_link2
translator_link3
translator_link4
translator_link5
translator_mask
translator_mask1
translator_mask2
translator_mask3
translator_mask4
translator_mask5
translators
type
url
url_access
url_status
via
volume
website
work
year
zbl
__find_number__()
__get_numbered_person__()
__get_numbered_persons__()
__parse_known_role_persons__()
__parse_roleless_persons__()
__validate_time__()
parse_persons()
}

class WikipediaPage{
language_code
page_id
pywikibot_page
pywikibot_site
references
title
wikimedia_event
wikimedia_site
url
__fix_class_key__()
__fix_aliases__()
__fix_dash__()
__fix_keys__()
__get_title_from_event__()
__get_wikipedia_page_from_event__()
__get_wikipedia_page_from_title__()
__parse_templates__()
extract_references()
}

class Person {
given
has_number
link
mask
name_string
number_in_sequence
orcid
role
surname
}

class Cache{
ssdb
add_reference()
check_reference_and_get_wikicitations_qid()
connect()
}

class SsdbDatabase{
connection
host
password
port
connect()
get()
set()
}

enum EnglishWikipediaTemplatePersonRole {
AUTHOR
EDITOR
HOST
INTERVIEWER
TRANSLATOR
UNKNOWN
}

@enduml