@startuml
'https://plantuml.com/component-diagram

[IARI] -- xhtml
[IARI] -- pdf
[IARI] -- references
[IARI] -- "reference/id"
[IARI] -- "check-url"
"check-url" --> url : lookup
[IARI] -- "check-doi"
[IARI] -- "article"
"check-doi" --> OpenAlex : lookup
"check-doi" --> FatCat : lookup
"check-doi" --> Wikidata : lookup
[IARI] -- all
"reference/id" <-- all
"check-doi" <-- all
"check-url" <-- all
"article" <-- all

database "file system" {

  folder "references/" {
  }
  folder "articles/" {
  }
  folder "urls/" {
  }
  folder "dois/" {
  }
  folder "xhtmls/" {
  }
  folder "pdfs/" {
  }

}
@enduml