@startuml
'https://plantuml.com/component-diagram

cloud "AWS" {
    package "Docker compose" {
        database "RabbitMQ container" {
          [rabbitmq] as RM
        }
'        [fastapi] as FA
        [wikicitations-api] as WA
'        [WikibaseIntegrator] as WBI
        [wcdimportbot ingestor] as WI
        [Wcdimportbot Celery Worker] as CW1
        [Wcdimportbot Celery Worker] as CW2
'        CW1 -- WBI : use
'        CW2 -- WBI : use
        PUBLISH -- RM
        WORKER --- RM : push jobs
        WORKER <--> CW1 : get/post
        WORKER <--> CW2 : get/post
'        WA - FA : use
        WA -> PUBLISH : submit job
        WA -- ADD_JOB
        WA -- GET_FROM_WDQID
        WA -- GET_ARTICLE_DETAILS
        WI --> PUBLISH : submit job
'        WI - WBI : use
    }
    database "SSDB" {
        [Cache] -up- SET
        [Cache] -- GET
        CW1 -> GET
        CW2 -> GET
        CW1 -> SET
        CW2 -> SET
    }
}

cloud "Wikimedia"{
  WI -> page_updates_API : read stream
  [Add job userscript] -> ADD_JOB
  [Issues userscript] --> GET_ARTICLE_DETAILS
  [Issues userscript] --> GET_FROM_WDQID
  [Go to WikiCitations item userscript] --> GET_FROM_WDQID
  [Enterprise API] -left- page_updates_API
}

database "Wikibase.cloud" {
    [WikiCitations] as WC
    WC - WB_API
    WC -- WB_SPARQL_API
    WA -> WB_SPARQL_API : query
    CW1 --> WB_API
    CW2 --> WB_API
}
@enduml