@startuml
'https://plantuml.com/component-diagram

cloud AWS {
    [Wikipedia dump] as WD
    [Graph generation script] as GGS
    GGS --> WD
    [wikicitations-api] as WA
    WA -- GET_WDQID
    WA -- GET_STATISTICS
}

cloud "Wikimedia"{
  WA --> page
  [Get statistics userscript] as US
  US --> GET_STATISTICS
  [Go to Wikipedia Citation Database item userscript] --> GET_WDQID
  [MediaWiki REST v1 API] -- page
}

database "Wikibase in Wikibase.cloud" {
    GGS --> HTTP_API
    [Wikipedia Citations Database] as WC
    WC -- CIRRUSSEARCH_ENDPOINT
    WC - HTTP_API
    WC -- SPARQL_API
    WA -----> SPARQL_API : query (slow)
}
@enduml