@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor user
control wcdimportbot_ingester
entity "Wikimedia Enterprise API - page updates" as enterprise_api
entity RabbitMQ as rabbitmq

user -> wcdimportbot_ingester :start
wcdimportbot_ingestor -> enterprise_api : listen for messages
loop got message
    wcdimportbot_ingester -> wcdimportbot_ingester : parse message
    alt got enwiki article
        wcdimportbot_ingester -> wcdimportbot_ingester : check if redirect
        alt not redirect
            wcdimportbot_ingester -> rabbitmq : publish message
        end
    end
end
@enduml