@startuml
'https://plantuml.com/activity-diagram-beta

start
:Write a userscript that gives the user an overview and detailed report about all quantifiable information based on
the article wikitext and inform the user about ways to improve the references;
:Write a new class WikipediaArticleDumpReader that can read articles from a compressed Wikipedia dump
:Write an AI/GROBID based reference reader that can convert plain text and mixed references to CS1 templates
:Invite the community to provide feedback on the framework;
:Define a process to let the community help guide what to improve iteratively;
stop

@enduml
