@startuml
'https://plantuml.com/activity-diagram-beta

start
:Write a userscript which informs the user about problems found with the references;
:Launch an enwiki-wcdbotworker in aws and add jobs from enwiki according to our filter into a work queue;
:Fix the worker so it support articles with >300 references;
:Publish all logging into kafka topics (nice to have);
:Invite the community to provide feedback on the framework;
:Scale up to hundreds->thousands->millions of articles;
:Define a process to let the community help guide what to improve iteratively;
stop

@enduml
