@startuml
'https://plantuml.com/sequence-diagram

'The databases are editable by the bot, the entity is not.

autonumber
actor User as user
control wcdimportbot
database "Cache/SPARQL" as Cache
database WikiCitations
entity "Wikipedia API" as wikipediaapi
user -> wcdimportbot: Run the bot using --import
wcdimportbot -> wikipediaapi: Get page data
wikipediaapi -> wcdimportbot: Response
wcdimportbot -> Cache: Lookup existing WCDQID
Cache -> wcdimportbot: Response
alt "page hash not found"
    wcdimportbot -> wcdimportbot: Parse templates into objects
    loop for each reference
        wcdimportbot -> wcdimportbot: tokenize/hash the reference
        wcdimportbot -> Cache: Lookup existing WCDQID
        Cache -> wcdimportbot: Response
        alt reference hash found
            wcdimportbot -> wcdimportbot: Link to existing reference
        end
        alt reference hash not found
            alt URL found
                wcdimportbot -> Cache: Lookup existing WCDQID to website item
                wcdimportbot -> wcdimportbot: Generate website item
                alt cache enabled
                    wcdimportbot -> Cache: Insert website item hash and WCDQID
                end
                wcdimportbot -> WikiCitations: Create new website item
                WikiCitations -> wcdimportbot: Response with new WCDQID
                wcdimportbot -> wcdimportbot: Link to website item from the reference
                wcdimportbot -> user: Print the URL to the new item.
            end
            wcdimportbot -> wcdimportbot: Generate the statements
            wcdimportbot -> WikiCitations: Create new item for the reference
            wcdimportbot -> user: Print the URL to the new item.
            alt cache enabled
                wcdimportbot -> Cache: Insert reference hash and WCDQID
            end
            WikiCitations -> wcdimportbot: Response with WCDQID
        end
    end
    wcdimportbot -> Cache: Insert page hash and WCDQID
    wcdimportbot -> wcdimportbot: Generate the statements
    wcdimportbot -> WikiCitations: Create new item for the page with links to all references
end
wcdimportbot -> user: Print the URL to the new page item and the Wikipedia article.
@enduml
