@startuml
'https://plantuml.com/sequence-diagram

autonumber
wcdimportbot -> "Wikipedia API": Get range of pages
loop for each page
    wcdimportbot -> wcdimportbot: Parse templates into objects
    loop for each reference
        wcdimportbot -> wcdimportbot: tokenize/hash the reference
        wcdimportbot -> MariaDB: Lookup reference hash
        MariaDB -> wcdimportbot: Response
        alt found
            wcdimportbot -> wcdimportbot: Link to existing reference
        end
        alt not found
            wcdimportbot -> WikiCitations: Create new item for the reference
            WikiCitations -> wcdimportbot: Response with QID
        end
    end
    wcdimportbot -> WikiCitations: Create new item for the page with links to all references
end
@enduml